apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
  labels:
    provider: postgress
    heritage: helm
    layer: data
    provisioner: spicter
    app: postgress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: main5311
        ports:
        - containerPort: 5432
