apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    provider: phpmyadmin
    heritage: helmc
    layer: data-admin
    provisioner: spicter
    app: phpmyadmin
spec:
  ports:
  - port: 80
  selector:
    provider: phpmyadmin
    
