{
  "apiVersion": "extensions/v1beta1",
  "kind": "DaemonSet",
  "metadata": {
    "name": "fluent-elasticsearch",
    "namespace": "kube-system",
    "labels": {
      "k8s-app": "fluentd-logging"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "fluentd-elasticsearch",
        "namespace": "kube-system",
        "labels": {
          "k8s-app": "fluentd-logging"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "fluentd-elasticsearch",
            "image": "falkonry/fluentd-elastic",
            "env": [
              {
                "name": ELASTIC_HOST,
                "value": elasticsearch-logging
              }
            ],
            "resources": {
              "limits": {
                "memory": "200Mi"
              },
              "requests": {
                "cpu": "100m",
                "memory": "200Mi"
              }
            },
            "volumeMounts": [
              {
                "name": "varlog",
                "mountPath": "/var/log"
              },
              {
                "name": "varlibdockercontainers",
                "mountPath": "/var/lib/docker/containers",
                "readOnly": true
              }
            ]
          }
        ],
        "terminationGracePeriodSeconds": 30,
        "volumes": [
          {
            "name": "varlog",
            "hostPath": {
              "path": "/var/log"
            }
          },
          {
            "name": "varlibdockercontainers",
            "hostPath": {
              "path": "/var/lib/docker/containers"
            }
          }
        ]
      }
    }
  }
}