---
apiVersion: "extensions/v1beta1"
kind: "DaemonSet"
metadata:
  labels:
    group: "io.fabric8.devops.apps"
    project: "fluentd"
    provider: "fabric8"
    version: "2.2.141"
  name: "fluentd"
spec:
  template:
    metadata:
      labels:
        group: "io.fabric8.devops.apps"
        project: "fluentd"
        provider: "fabric8"
        version: "2.2.141"
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: "ELASTICSEARCH_HOST"
          value: "elasticsearch"
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        image: "fabric8/fluentd-kubernetes:v1.12"
        name: "fluentd"
        ports: []
        resources:
          limits:
            cpu: "100m"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/log"
          name: "varlog"
        - mountPath: "/var/lib/docker/containers"
          name: "varlibdockercontainers"
          readOnly: true
      imagePullSecrets: []
      serviceAccountName: "fluentd"
      volumes:
      - hostPath:
          path: "/var/log"
        name: "varlog"
      - hostPath:
          path: "/var/lib/docker/containers"
        name: "varlibdockercontainers"

