apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  selector:
    component: elasticsearch
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9200
    
