apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    project: "elasticsearch"
    provider: "fabric8"
    version: "2.2.141"
    group: "io.fabric8.devops.apps"
    package: "logging"
  name: "elasticsearch"
  namespace: kube-system
spec:
  deprecatedPublicIPs: []
  externalIPs: []
  ports:
  - port: 9200
    protocol: "TCP"
    targetPort: 9200
    nodePort: 30064
  selector:
    project: "elasticsearch"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
  type: "NodePort"
