apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    project: "kibana"
    provider: "fabric8"
    version: "2.2.141"
    group: "io.fabric8.devops.apps"
    package: "logging"
  name: "kibana"
  namespace: default
spec:
  deprecatedPublicIPs: []
  externalIPs: []
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 5601
    nodePort: 30062
  selector:
    project: "kibana"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
  type: "NodePort"
