name: fluentd
from:
  name: fluentd
  version: 2.2.142-SNAPSHOT
  repo: https://github.com/fabric8io/charts.git
home: http://fabric8.io/fluentd/
version: 2.2.142-SNAPSHOT
description: '[Fluentd](http://www.fluentd.org/) is an open source data collector
  for unified logging layer.'
maintainers:
- Fabric8 Development Team <fabric8@googlegroups.com>
