apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    provider: mariadb
    heritage: helm
    layer: data
    provisioner: spicter
    app: mariadb
spec:
  ports:
  - port: 3306
  selector:
    provider: mariadb
