apiVersion: v1
kind: ReplicationController
metadata:
  name: wekan
  labels:
    provider: mekan
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mekan
    spec:
      containers:
      - name: mekan
        image: mquandalle/wekan
#        env:
#        - name: MYSQL_ROOT_PASSWORD
#          value: mypassword
        ports:
        - containerPort: 80