apiVersion: v1
kind: ReplicationController
metadata:
  name: wekan
  labels:
    provider: wekan
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: wekan
    spec:
      containers:
      - name: wekan
        image: mquandalle/wekan
        env:
#        - name: MYSQL_ROOT_PASSWORD
#          value: mypassword
        - name: MONGO_URL
          value: mongodb://root:main5311@mongodb:27017/wekan
        - name: ROOT_URL 
          value: http://localhost:8008/api/v1/proxy/namespaces/default/services/wekan
        ports:
        - containerPort: 80