apiVersion: v1
kind: Service
metadata:
  name: mywebsql
  labels:
    provider: mywebsql
    heritage: helmc
    layer: data-admin
    provisioner: spicter
    app: mywebsql
spec:
  ports:
  - port: 80
  selector:
    provider: mywebsql
    
