apiVersion: v1
kind: ReplicationController
metadata:
  name: mywebsql
  labels:
    provider: mywebsql
    heritage: helmc
    layer: data-admin
    provisioner: spicter
    app: mywebsql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mywebsql
    spec:
      containers:
      - name: mywebsql
        image: jacksoncage/phppgadmin
        env:
        - name: POSTGRES_HOST
          value: postgresql
