apiVersion: v1
kind: Service
metadata:
  name: ldap-wso2
  labels:
    provider: ldap-wso2
    heritage: helm
    layer: data
    provisioner: spicter
    app: ldap-wso2
spec:
  ports:
  - port: 80
    targetPort: 9443
  selector:
    provider: ldap-wso2
