apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
  labels:
    provider: mongodb
    heritage: helm
    layer: data
    provisioner: spicter
    app: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mongodb
    spec:
      containers:
      - name: mongodb
        image: frodenas/mongodb
        env:
        - name: MONGODB_USERNAME
          value: root
        - name: MONGODB_PASSWORD
          value: main5311
        - name: MONGODB_DBNAME
          value: wekan          
        ports:
        - containerPort: 27017